// Post-build step: adapter-cloudflare writes the app bundle to wrangler's
// `main` path and offers no hook for extra exports, so this wraps that bundle
// to add the `scheduled` handler for the weekly digest push cron. Runs after
// `vite build` (see the build script in package.json).
import { copyFileSync, existsSync, writeFileSync } from 'node:fs';

const dir = '.svelte-kit/cloudflare';
const bundle = `${dir}/_worker.js`;
const appWorker = `${dir}/_app_worker.js`;

if (!existsSync(bundle)) {
	console.error('wrap-worker: missing', bundle, '— run `vite build` first.');
	process.exit(1);
}

copyFileSync(bundle, appWorker);
writeFileSync(
	bundle,
	`// Generated by scripts/wrap-worker.mjs — do not edit.
import worker from './_app_worker.js';

export default {
	fetch: worker.fetch,
	async scheduled(_controller, env, ctx) {
		const secret = env.WEEKLY_PUSH_SECRET;
		if (!secret) return;
		const request = new Request('https://synapse.local/api/weekly-push/run', {
			method: 'POST',
			headers: { 'x-push-secret': secret }
		});
		await worker.fetch(request, env, ctx);
	}
};
`
);
console.log('wrap-worker: added scheduled handler to', bundle);
